scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_mixed_single_randh.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_mixed_single_randh --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidaraug_m_s_randh_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_mixed_single.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_mixed_single --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidaraug_m_s_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidaraug_s_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidaraug_s_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_dethead_0p8w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_dethead_0p8w --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_det8_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_dethead_0p5w --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_det5_s_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/sc_lidar_s_randh_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_v32_randh.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_v32_randh --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidar_s_v32_randh_$(date +%Y-%m-%d_%H:%M).out 2>&1



# scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p8w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p8w --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidar_s_randh_det0p8_$(date +%Y-%m-%d_%H:%M).out 2>&1
# scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p8w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p8w_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidar_s_randh_det0p8_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/sc_lidar_s_randh_det0p5_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/sc_lidar_s_randh_det0p5_t2_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1


scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_depthcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_depthcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/dc_lidar_s_randh_det0p5_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_depthcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_depthcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/dc_lidar_s_randh_det0p5_t2_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_depthcontrast_waymo10.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_depthcontrast_waymo10 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/dc_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_depthcontrast_waymo10.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_depthcontrast_waymo10_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/dc_fine5_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_try2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/sc_fine5_try2_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/sc_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_pointrcnn_segcontrast_waymo10.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name pointrcnn_pretrain_segcontrast_waymo10_try2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_point_try2_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_pointrcnn_segcontrast_waymo10.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name pointrcnn_pretrain_segcontrast_waymo10 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_point_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_pointrcnn_segcontrast_waymo10_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name pointrcnn_pretrain_segcontrast_waymo10_dethead_0p5w_try2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_point_det_try2_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_pointrcnn_segcontrast_waymo10_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name pointrcnn_pretrain_segcontrast_waymo10_dethead_0p5w --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_point_det_$(date +%Y-%m-%d_%H:%M).out 2>&1


# scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_det_single_branch.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_det_single_branch --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidar_det_singlehead_$(date +%Y-%m-%d_%H:%M).out 2>&1
# scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_det_single_branch.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_det_single_branch_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidar_det_singlehead_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_proposalcontrast_waymo10.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_proposalcontrast_waymo10 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/pc_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_proposalcontrast_waymo10.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_proposalcontrast_waymo10_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/pc_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_proposalcontrast_waymo10.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_proposalcontrast_waymo10 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/pc_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_proposalcontrast_waymo10.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_proposalcontrast_waymo10_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/pc_fine5_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1


scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_reghead.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_reghead --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/screg_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_reghead.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_reghead_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/screg_fine5_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_scratch_minkunet.yaml --mode scratch --finetune_epochs 15 --other_datasets --downstream_model_dir scratch_5percent --frame_sampling_div 5 > ./output/log/scratch_5perc_semkitti_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_scratch_minkunet.yaml --mode scratch --finetune_epochs 15 --other_datasets --downstream_model_dir scratch_5percent_try2 --frame_sampling_div 5 > ./output/log/scratch_5perc_semkitti_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1


scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_scratch_minkunet.yaml --mode scratch --finetune_epochs 15 --other_datasets --downstream_model_dir scratch_1percent > ./output/log/scratch_1perc_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_scratch_minkunet.yaml --mode scratch --finetune_epochs 15 --other_datasets --downstream_model_dir scratch_1percent_try2 > ./output/log/scratch_1perc_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/sc_lidar_s_randh_t2_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_dethead_0p5w_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/sc_det5_t2_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_dethead_0p5w --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/sc_det5_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_mixed.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_mixed --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidaraug_mixed_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_mixed.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_mixed_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidaraug_mixed_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/sc_lidar_s_randh_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_v32_randh.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_v32_randh --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidar_s_v32_randh_$(date +%Y-%m-%d_%H:%M).out 2>&1

#time test
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10.yaml --pretrain_epochs 10 --model_name minkunet_pretrain_segcontrast_waymo10_ep10_time > ./output/log/sc_ep10_time_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w.yaml --pretrain_epochs 10 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w_ep10_time > ./output/log/sc_lidar_s_randh_det0p5_ep10_time_$(date +%Y-%m-%d_%H:%M).out 2>&1

#200 epochs
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10.yaml --pretrain_epochs 200 --model_name minkunet_pretrain_segcontrast_waymo10_ep200_t2 --other_datasets --pretrained_ckpt checkpoint-ep199.pth.tar > ./output/log/sc_ep200_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w.yaml --pretrain_epochs 200 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w_ep200_t2 --other_datasets --pretrained_ckpt checkpoint-ep199.pth.tar > ./output/log/sc_lidar_s_randh_det0p5_ep200_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_dethead_0p5w.yaml --pretrain_epochs 200 --model_name minkunet_pretrain_segcontrast_waymo10_dethead_0p5w_ep200_t2 --other_datasets --pretrained_ckpt checkpoint-ep199.pth.tar > ./output/log/sc_det0p5_ep200_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh.yaml --pretrain_epochs 200 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh_ep200_t2 --other_datasets --pretrained_ckpt checkpoint-ep199.pth.tar > ./output/log/sc_lidar_s_randh_ep200_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_or_dethead_0p5w.yaml --pretrain_epochs 200 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_or_dethead_0p5w_ep200 --other_datasets --pretrained_ckpt checkpoint-ep199.pth.tar > ./output/log/sc_lidar_or_det0p5_ep200_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_depthcontrast_waymo10.yaml --pretrain_epochs 200 --model_name minkunet_pretrain_depthcontrast_waymo10_ep200 --other_datasets --pretrained_ckpt checkpoint-ep199.pth.tar > ./output/log/dc_ep200_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_depthcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w.yaml --pretrain_epochs 200 --model_name minkunet_pretrain_depthcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w_ep200 --other_datasets --pretrained_ckpt checkpoint-ep199.pth.tar > ./output/log/dc_lidar_s_randh_det0p5_ep200_$(date +%Y-%m-%d_%H:%M).out 2>&1

#200 epochs finetune on 5% labels
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh_ep200_t2 --other_datasets --pretrained_ckpt checkpoint-ep199.pth.tar --frame_sampling_div 5 > ./output/log/sc_lidar_s_randh_ep200_t2_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_ep200 --other_datasets --pretrained_ckpt checkpoint-ep199.pth.tar --frame_sampling_div 5 > ./output/log/sc_ep200_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_ep200_t2 --other_datasets --pretrained_ckpt checkpoint-ep199.pth.tar --frame_sampling_div 5 > ./output/log/sc_ep200_t2_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w_ep200 --other_datasets --pretrained_ckpt checkpoint-ep199.pth.tar --frame_sampling_div 5 > ./output/log/sc_lidar_s_randh_det0p5_ep200_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_dethead_0p5w_ep200_t2 --other_datasets --pretrained_ckpt checkpoint-ep199.pth.tar --frame_sampling_div 5 > ./output/log/sc_det0p5_ep200_t2_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w_ep200_t2 --other_datasets --pretrained_ckpt checkpoint-ep199.pth.tar --frame_sampling_div 5 > ./output/log/sc_lidar_s_randh_det0p5_ep200_t2_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1


# scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10.yaml --finetune_epochs 100 --model_name minkunet_pretrain_segcontrast_waymo10 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_fine1perc_100ep_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w.yaml --finetune_epochs 100 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh_dethead_0p5w_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidar_s_randh_det0p5_t2_fine1perc_100ep_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_or_dethead_0p5w.yaml --finetune_epochs 100 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_or_dethead_0p5w --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidar_or_det0p5_fine1perc_100ep_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10.yaml --finetune_epochs 100 --model_name minkunet_pretrain_segcontrast_waymo10_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_t2_fine1perc_100ep_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_dethead_0p5w.yaml --finetune_epochs 100 --model_name minkunet_pretrain_segcontrast_waymo10_dethead_0p5w_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_det5_t2_fine1perc_100ep_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_or_dethead_0p5w.yaml --finetune_epochs 100 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_or_dethead_0p5w_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidar_or_det0p5_t2_fine1perc_100ep_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh.yaml --finetune_epochs 100 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidar_fine1perc_100ep_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_dethead_0p5w.yaml --finetune_epochs 100 --model_name minkunet_pretrain_segcontrast_waymo10_dethead_0p5w --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_det5_fine1perc_100ep_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_single_randh.yaml --finetune_epochs 100 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_single_randh_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_lidar_fine1perc_100ep_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_scratch_minkunet.yaml --mode scratch --finetune_epochs 100 --other_datasets --downstream_model_dir scratch_1percent_100epochs > ./output/log/scratch_1perc_100ep_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_scratch_minkunet.yaml --mode scratch --finetune_epochs 100 --other_datasets --downstream_model_dir scratch_1percent_100epochs_t2 > ./output/log/scratch_1perc_100ep_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_or_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_or_dethead_0p5w --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/sc_lidar_OR_det0p5_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_or_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_or_dethead_0p5w_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/sc_lidar_OR_det0p5_t2_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_depthcontrast_waymo10_lidar_aug_or_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_depthcontrast_waymo10_lidar_aug_or_dethead_0p5w --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/dc_lidar_OR_det0p5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_depthcontrast_waymo10_lidar_aug_or_dethead_0p5w.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_depthcontrast_waymo10_lidar_aug_or_dethead_0p5w_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/dc_lidar_OR_det0p5_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_gt_segcontrast_waymo7p5.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_gt_segcontrast_waymo7p5 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/sc_gt_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_gt_segcontrast_waymo7p5.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_gt_segcontrast_waymo7p5_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/sc_gt_t2_fine5_$(date +%Y-%m-%d_%H:%M).out 2>&1

scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_gt_segcontrast_waymo7p5.yaml --finetune_epochs 100 --model_name minkunet_pretrain_gt_segcontrast_waymo7p5 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_gt_fine1perc_100ep_$(date +%Y-%m-%d_%H:%M).out 2>&1
scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_gt_segcontrast_waymo7p5.yaml --finetune_epochs 100 --model_name minkunet_pretrain_gt_segcontrast_waymo7p5_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar > ./output/log/sc_gt_t2_fine1perc_100ep_$(date +%Y-%m-%d_%H:%M).out 2>&1

# scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_or_dethead_0p5w_p0p3.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_or_dethead_0p5w_p0p3 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/sc_lidar_OR_det0p5_p0p3_$(date +%Y-%m-%d_%H:%M).out 2>&1
# scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file configs/waymo_minkunet_segcontrast_waymo10_lidar_aug_or_dethead_0p5w_p0p3.yaml --pretrain_batchsize_per_gpu 16 --finetune_batchsize_per_gpu 8 --model_name minkunet_pretrain_segcontrast_waymo10_lidar_aug_or_dethead_0p5w_p0p3_t2 --other_datasets --pretrained_ckpt checkpoint-ep49.pth.tar --frame_sampling_div 5 > ./output/log/sc_lidar_OR_det0p5_p0p3_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1

# To see hanging threads
#ps -ef | grep -i '[p]ython'
pids=$(ps aux | grep 'nisarbar' | grep 'python' | awk '{print $2}')
echo "$pids" | xargs kill