# In progress:
# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-2%1 --job-name=segcontrast_lower_bs scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19319 --cfg_file configs/waymo_pointrcnn_backbone_segcontrast_lower_bs_epochs_data.yaml
# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-2%1 --job-name=iou_thresh_0p6_lower_bs scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19316 --cfg_file configs/waymo_pointrcnn_backbone_iou_thresh_0p6_lower_bs_epochs_data.yaml
# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=vfh_thresh_0p2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19210 --cfg_file configs/waymo_pointrcnn_backbone_vfh_thresh_0p2.yaml

# Done
# sbatch --time=17:00:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=esf_thresh_0p2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19212 --cfg_file configs/waymo_pointrcnn_backbone_esf_thresh_0p2.yaml
# sbatch --time=17:00:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=vfh_weight scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19214 --cfg_file configs/waymo_pointrcnn_backbone_vfh_weight.yaml
# sbatch --time=6:00:00 --mem=250G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=esf_weight scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19215 --cfg_file configs/waymo_pointrcnn_backbone_esf_weight.yaml

# In progress:
#sbatch --time=6:00:00  --nodes=1 --ntasks=1 --array=1-3%1 --job-name=iou_weight scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19338 --cfg_file configs/waymo_pointrcnn_backbone_iou_weight.yaml
#sbatch --time=6:00:00  --gres=gpu:t4:4 --mem=100G --nodes=1 --ntasks=1 --array=1-3%1 --job-name=iou_weight scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19338 --cfg_file configs/waymo_pointrcnn_backbone_iou_weight.yaml
#sbatch --time=6:00:00  --gres=gpu:v100:8 --mem=100G --nodes=1 --ntasks=1 --array=1-3%1 --job-name=iou_weight scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19338 --cfg_file configs/waymo_pointrcnn_backbone_iou_weight.yaml

# sbatch --time=3:00:00  --dependency=afterany:13839570 --gres=gpu:t4:4 --mem=100G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=lpseg_segcontrast scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19319 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_segcontrast.yaml
# sbatch --time=6:00:00 --gres=gpu:t4:4 --mem=100G --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_iou_perc_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19324 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_perc_0p1.yaml
# sbatch --time=6:00:00 --gres=gpu:t4:4 --mem=100G --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_vfh_perc_0p05 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19523 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_vfh_perc_0p05.yaml
# sbatch --time=6:00:00 --gres=gpu:t4:4 --mem=100G --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_vfh_perc_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19524 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_vfh_perc_0p1.yaml

# sbatch --time=6:00:00 --gres=gpu:t4:4 --mem=100G --nodes=1 --ntasks=1 --array=1-2%1 --job-name=lpseg_vfh_thresh_0p2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19210 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_vfh_thresh_0p2.yaml
# sbatch --time=6:00:00 --gres=gpu:t4:4 --mem=100G --nodes=1 --ntasks=1 --array=1-2%1 --job-name=lpseg_iou_perc_0p05 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19323 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_perc_0p05.yaml
# sbatch --time=6:00:00 --gres=gpu:t4:4 --mem=100G --nodes=1 --ntasks=1 --array=1-2%1 --job-name=lpseg_iou_weight scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19338 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_weight.yaml
# sbatch --time=6:00:00 --gres=gpu:t4:4 --mem=100G --nodes=1 --ntasks=1 --array=1-4%1 --job-name=lpseg_esf_perc_0p05 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19423 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_esf_perc_0p05.yaml
# sbatch --time=6:00:00 --gres=gpu:t4:4 --mem=100G --nodes=1 --ntasks=1 --array=1-4%1 --job-name=lpseg_esf_perc_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19424 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_esf_perc_0p1.yaml

# try cedar
# sbatch --time=9:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=lpseg_iou_perc_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19324 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_perc_0p1.yaml
# sbatch --time=6:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_vfh_perc_0p05 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19523 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_vfh_perc_0p05.yaml
# sbatch --time=6:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_vfh_perc_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19524 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_vfh_perc_0p1.yaml

# sbatch --time=6:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_vfh_thresh_0p2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19210 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_vfh_thresh_0p2.yaml
# sbatch --time=6:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_iou_perc_0p05 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19323 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_perc_0p05.yaml
#sbatch --time=6:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_iou_weight scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19338 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_weight.yaml
# sbatch --time=6:00:00 --dependency=afterany:21243692 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-4%1 --job-name=lpseg_esf_perc_0p05 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19423 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_esf_perc_0p05.yaml
# sbatch --time=6:00:00 --dependency=afterany:21243695 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-4%1 --job-name=lpseg_esf_perc_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19424 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_esf_perc_0p1.yaml
# sbatch --time=6:00:00 --dependency=afterany:21243703 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-4%1 --job-name=lpseg_iou_perc_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19425 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_perc_0p3.yaml
# sbatch --time=6:00:00 --dependency=afterany:21243705 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-4%1 --job-name=lpseg_iou_perc_0p4 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19426 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_perc_0p4.yaml
# sbatch --time=6:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-2%1 --job-name=lpseg_esf_perc_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19427 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_esf_perc_0p3.yaml
# sbatch --time=2:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=lpseg_esf_perc_0p4 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19428 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_esf_perc_0p4.yaml

# sbatch --time=10:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-2%1 --job-name=lpseg_iou_perc_0p2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19325 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_perc_0p2.yaml
# sbatch --time=10:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-2%1 --job-name=lpseg_iou_perc_0p5 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19326 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_perc_0p5.yaml
# sbatch --time=10:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-2%1 --job-name=lpseg_iou_perc_0p3_esf_wt scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19327 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_perc_0p3_esf_weight.yaml
# sbatch --time=10:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=100G --nodes=1 --ntasks=1 --array=1-2%1 --job-name=lpseg_iou_perc_0p3_iou_wt scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19328 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_perc_0p3_iou_weight.yaml
 

# sbatch --dependency=afterany:23627050 --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_segcontrast scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19319 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_segcontrast.yaml
# sbatch --dependency=afterany:23627049 --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_iou_thresh_0p6 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19316 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_thresh_0p6.yaml
# sbatch --dependency=afterany:23627051 --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_vfh_thresh_0p2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19210 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_vfh_thresh_0p2.yaml

# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_esf_thresh_0p2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19212 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_esf_thresh_0p2.yaml
# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_vfh_weight scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19214 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_vfh_weight.yaml
# sbatch --time=6:00:00 --dependency=afterany:23807305 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=lpseg_esf_weight scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19215 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_esf_weight.yaml

# In progress:
# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=lpseg_iou_weight scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19338 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_weight.yaml


# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=iou_perc_0p05 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19323 --cfg_file configs/waymo_pointrcnn_backbone_iou_perc_0p05.yaml
# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=iou_perc_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19324 --cfg_file configs/waymo_pointrcnn_backbone_iou_perc_0p1.yaml
# sbatch --time=2:00:00 --nodes=1 --ntasks=1 --array=1-9%1 --job-name=iou_perc_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19325 --cfg_file configs/waymo_pointrcnn_backbone_iou_perc_0p3.yaml
# sbatch --time=2:00:00 --nodes=1 --ntasks=1 --array=1-9%1 --job-name=iou_perc_0p4 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19326 --cfg_file configs/waymo_pointrcnn_backbone_iou_perc_0p4.yaml
# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=iou_perc_0p2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19325 --cfg_file configs/waymo_pointrcnn_backbone_iou_perc_0p2.yaml
# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=iou_perc_0p5 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19326 --cfg_file configs/waymo_pointrcnn_backbone_iou_perc_0p5.yaml
# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=iou_perc_0p3_esf_wt scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19327 --cfg_file configs/waymo_pointrcnn_backbone_iou_perc_0p3_esf_weight.yaml
# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=iou_perc_0p3_iou_wt scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19328 --cfg_file configs/waymo_pointrcnn_backbone_iou_perc_0p3_iou_weight.yaml

# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=esf_perc_0p05 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19423 --cfg_file configs/waymo_pointrcnn_backbone_esf_perc_0p05.yaml
# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=esf_perc_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19424 --cfg_file configs/waymo_pointrcnn_backbone_esf_perc_0p1.yaml
# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-2%1 --job-name=esf_perc_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19425 --cfg_file configs/waymo_pointrcnn_backbone_esf_perc_0p3.yaml
# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-2%1 --job-name=esf_perc_0p4 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19426 --cfg_file configs/waymo_pointrcnn_backbone_esf_perc_0p4.yaml

# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=vfh_perc_0p05 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19523 --cfg_file configs/waymo_pointrcnn_backbone_vfh_perc_0p05.yaml
# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=vfh_perc_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19524 --cfg_file configs/waymo_pointrcnn_backbone_vfh_perc_0p1.yaml

# In progress:
# sbatch --dependency=afterany:23653292 --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_iou_perc_0p05 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19323 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_perc_0p05.yaml
# sbatch --dependency=afterany:23653293 --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_iou_perc_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19324 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_iou_perc_0p1.yaml

# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-2%1 --job-name=lpseg_esf_perc_0p05 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19423 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_esf_perc_0p05.yaml
# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-2%1 --job-name=lpseg_esf_perc_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19424 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_esf_perc_0p1.yaml

# sbatch --dependency=afterany:23653296 --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_vfh_perc_0p05 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19523 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_vfh_perc_0p05.yaml
# sbatch --dependency=afterany:23653297 --time=6:00:00 --nodes=1 --ntasks=1 --array=1-3%1 --job-name=lpseg_vfh_perc_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19524 --downstream --cfg_file configs/waymo_lpseg_pointrcnn_backbone_vfh_perc_0p1.yaml




################################### MinkUnet
# sbatch --time=14:00:00 --dependency=afterany:21479439 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=2 --ntasks=2 --array=1-1%1 --job-name=mink_segcontrast scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19520 --cfg_file configs/waymo_minkunet_segcontrast.yaml

# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-6%1 --job-name=mink_esf_perc_0p05 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19521 --cfg_file configs/waymo_minkunet_esf_perc_0p05.yaml
#sbatch --time=1:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=mink_esf_perc_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19522 --cfg_file configs/waymo_minkunet_esf_perc_0p1.yaml
# sbatch --time=6:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-6%1 --job-name=mink_esf_perc_0p2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19523 --cfg_file configs/waymo_minkunet_esf_perc_0p2.yaml
# sbatch --time=6:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-6%1 --job-name=mink_esf_perc_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19524 --cfg_file configs/waymo_minkunet_esf_perc_0p3.yaml
#sbatch --time=6:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-6%1 --job-name=mink_esf_perc_0p4 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19525 --cfg_file configs/waymo_minkunet_esf_perc_0p4.yaml

# sbatch --time=6:00:00 --nodes=1 --ntasks=1 --array=1-6%1 --job-name=mink_iou_perc_0p05 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19529 --cfg_file configs/waymo_minkunet_iou_perc_0p05.yaml
# sbatch --time=6:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-6%1 --job-name=mink_iou_perc_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19530 --cfg_file configs/waymo_minkunet_iou_perc_0p1.yaml
#sbatch --time=12:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=mink_iou_perc_0p2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19531 --cfg_file configs/waymo_minkunet_iou_perc_0p2.yaml
# sbatch --time=12:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=2 --ntasks=2 --array=1-6%1 --job-name=mink_iou_perc_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19532 --cfg_file configs/waymo_minkunet_iou_perc_0p3.yaml
# sbatch --time=6:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-6%1 --job-name=mink_iou_perc_0p4 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19533 --cfg_file configs/waymo_minkunet_iou_perc_0p4.yaml

# sbatch --time=10:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=lpseg_mink_segcontrast scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19521 --downstream --cfg_file configs/waymo_lpseg_minkunet_segcontrast.yaml --linear_probe_last_n_ckpts 10
# sbatch --time=10:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=lpseg_mink_iou_perc_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19522 --downstream --cfg_file configs/waymo_lpseg_minkunet_iou_perc_0p3.yaml --linear_probe_last_n_ckpts 10

### pretrained on 5% waymo
sbatch --time=2:00:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=esf_thresh_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19211 --cfg_file configs/waymo_pointrcnn_backbone_esf_thresh_0p1.yaml
sbatch --time=3:00:00 --nodes=1 --ntasks=1 --array=1-6%1 --job-name=esf_thresh_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19212 --cfg_file configs/waymo_pointrcnn_backbone_esf_thresh_0p3.yaml
sbatch --time=3:00:00 --nodes=1 --ntasks=1 --array=1-6%1 --job-name=esf_thresh_0p4 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19213 --cfg_file configs/waymo_pointrcnn_backbone_esf_thresh_0p4.yaml
sbatch --time=3:00:00 --nodes=1 --ntasks=1 --array=1-6%1 --job-name=esf_perc_0p2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19214 --cfg_file configs/waymo_pointrcnn_backbone_esf_perc_0p2.yaml
sbatch --time=3:00:00 --nodes=1 --ntasks=1 --array=1-6%1 --job-name=esf_perc_0p5 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19215 --cfg_file configs/waymo_pointrcnn_backbone_esf_perc_0p5.yaml

sbatch --time=3:00:00 --nodes=1 --ntasks=1 --array=1-6%1 --job-name=iou_thresh_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19216 --cfg_file configs/waymo_pointrcnn_backbone_iou_thresh_0p3.yaml
sbatch --time=3:00:00 --nodes=1 --ntasks=1 --array=1-6%1 --job-name=iou_thresh_0p4 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19217 --cfg_file configs/waymo_pointrcnn_backbone_iou_thresh_0p4.yaml
sbatch --time=3:00:00 --nodes=1 --ntasks=1 --array=1-6%1 --job-name=iou_thresh_0p5 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19218 --cfg_file configs/waymo_pointrcnn_backbone_iou_thresh_0p5.yaml
sbatch --time=3:00:00 --nodes=1 --ntasks=1 --array=1-6%1 --job-name=iou_thresh_0p7 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19219 --cfg_file configs/waymo_pointrcnn_backbone_iou_thresh_0p7.yaml


sbatch --time=5:00:00 --nodes=1 --ntasks=1 --array=1-6%1 --job-name=iou_perc_0p05_iou_wt_w3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19216 --cfg_file configs/waymo_pointrcnn_backbone_iou_perc_0p05_iou_wt.yaml
sbatch --time=5:00:00 --nodes=1 --ntasks=1 --array=1-6%1 --job-name=iou_perc_0p05_esf_wt_w3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19217 --cfg_file configs/waymo_pointrcnn_backbone_iou_perc_0p05_esf_wt.yaml
sbatch --time=5:00:00 --nodes=1 --ntasks=1 --array=1-6%1 --job-name=esf_perc_0p3_iou_wt_w3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19218 --cfg_file configs/waymo_pointrcnn_backbone_esf_perc_0p3_iou_wt.yaml
sbatch --time=5:00:00 --nodes=1 --ntasks=1 --array=1-6%1 --job-name=esf_perc_0p3_esf_wt_w3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19219 --cfg_file configs/waymo_pointrcnn_backbone_esf_perc_0p3_esf_wt.yaml

# sbatch --time=1:30:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_esf_thresh_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19211 --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --downstream  --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_thresh_0p1
# sbatch --time=1:30:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_esf_thresh_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19212 --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --downstream  --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_thresh_0p3
# sbatch --time=1:30:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_esf_thresh_0p4 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19213 --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --downstream  --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_thresh_0p4
# sbatch --time=1:30:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_esf_perc_0p2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19214 --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --downstream  --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_perc_0p2
# sbatch --time=1:30:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_esf_perc_0p5 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19215 --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --downstream  --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_perc_0p5


# #minkunet-pretrained on 5% waymo - finetune one lr on 1% waymo 
sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_e15_mink_segcontrast scripts/submit_ddp_cedar.sh --tcp_port 19641 --downstream --cfg_file configs/waymo_fine1lr_minkunet_segcontrast.yaml --pretrained_ckpt checkpoint-ep99.pth.tar
sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_e15_mink_iou_perc_0p3 scripts/submit_ddp_cedar.sh --tcp_port 19651 --downstream --cfg_file configs/waymo_fine1lr_minkunet_iou_perc_0p3.yaml --pretrained_ckpt checkpoint-ep99.pth.tar
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine1lr_e30_mink_segcontrast scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19641 --downstream --cfg_file configs/waymo_fine1lr_minkunet_segcontrast.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 30
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine1lr_e30_mink_iou_perc_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19651 --downstream --cfg_file configs/waymo_fine1lr_minkunet_iou_perc_0p3.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 30
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine1lr_e60_mink_segcontrast scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19641 --downstream --cfg_file configs/waymo_fine1lr_minkunet_segcontrast.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 60
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine1lr_e60_mink_iou_perc_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19651 --downstream --cfg_file configs/waymo_fine1lr_minkunet_iou_perc_0p3.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 60
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine1lr_e100_mink_segcontrast scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19641 --downstream --cfg_file configs/waymo_fine1lr_minkunet_segcontrast.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 100
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine1lr_e100_mink_iou_perc_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19651 --downstream --cfg_file configs/waymo_fine1lr_minkunet_iou_perc_0p3.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 100

# #minkunet-pretrained on 5% waymo - finetune 2lrs on 1% waymo
sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine2lrs_e15_mink_segcontrast scripts/submit_ddp_cedar.sh --tcp_port 19661 --downstream --cfg_file configs/waymo_fine2lrs_minkunet_segcontrast.yaml --pretrained_ckpt checkpoint-ep99.pth.tar
sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine2lrs_e15_mink_iou_perc_0p3 scripts/submit_ddp_cedar.sh --tcp_port 19671 --downstream --cfg_file configs/waymo_fine2lrs_minkunet_iou_perc_0p3.yaml --pretrained_ckpt checkpoint-ep99.pth.tar
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine2lrs_e30_mink_segcontrast scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19661 --downstream --cfg_file configs/waymo_fine2lrs_minkunet_segcontrast.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 30
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine2lrs_e30_mink_iou_perc_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19671 --downstream --cfg_file configs/waymo_fine2lrs_minkunet_iou_perc_0p3.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 30
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine2lrs_e60_mink_segcontrast scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19661 --downstream --cfg_file configs/waymo_fine2lrs_minkunet_segcontrast.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 60
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine2lrs_e60_mink_iou_perc_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19671 --downstream --cfg_file configs/waymo_fine2lrs_minkunet_iou_perc_0p3.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 60
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine2lrs_e100_mink_segcontrast scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19661 --downstream --cfg_file configs/waymo_fine2lrs_minkunet_segcontrast.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 100
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine2lrs_e100_mink_iou_perc_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19671 --downstream --cfg_file configs/waymo_fine2lrs_minkunet_iou_perc_0p3.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 100

sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_segcontrast scripts/submit_ddp_cedar.sh --tcp_port 19681 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_segcontrast_lower_bs_epochs_data
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_iou_perc_0p3 scripts/submit_ddp_cedar.sh --tcp_port 19682 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p3
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_esf_perc_0p3 scripts/submit_ddp_cedar.sh --tcp_port 19683 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_perc_0p3
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_esf_perc_0p05 scripts/submit_ddp_cedar.sh --tcp_port 19684 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_perc_0p05
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_esf_perc_0p1 scripts/submit_ddp_cedar.sh --tcp_port 19685 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_perc_0p1
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_esf_perc_0p4 scripts/submit_ddp_cedar.sh --tcp_port 19686 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_perc_0p4
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_esf_weight scripts/submit_ddp_cedar.sh --tcp_port 19687 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_weight
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_iou_perc_0p05 scripts/submit_ddp_cedar.sh --tcp_port 19688 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p05
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_iou_perc_0p1 scripts/submit_ddp_cedar.sh --tcp_port 19689 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p1
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_iou_perc_0p2 scripts/submit_ddp_cedar.sh --tcp_port 19690 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p2
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_iou_perc_0p4 scripts/submit_ddp_cedar.sh --tcp_port 19691 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p4
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_iou_perc_0p5 scripts/submit_ddp_cedar.sh --tcp_port 19692 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p5
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_iou_weight scripts/submit_ddp_cedar.sh --tcp_port 19693 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_weight
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_iou_perc_0p3_iou_wt scripts/submit_ddp_cedar.sh --tcp_port 19694 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p3_iou_weight
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_perc_0p3_esf_wt scripts/submit_ddp_cedar.sh --tcp_port 19695 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p3_esf_weight
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_iou_thresh_0p6 scripts/submit_ddp_cedar.sh --tcp_port 19696 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_thresh_0p6_lower_bs_epochs_data
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine2lrs_ptrcnn_esf_thresh_0p2 scripts/submit_ddp_cedar.sh --tcp_port 19697 --downstream --cfg_file configs/waymo_fine2lrs_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_thresh_0p2

sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_segcontrast scripts/submit_ddp_cedar.sh --tcp_port 19581 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_segcontrast_lower_bs_epochs_data
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_iou_perc_0p3 scripts/submit_ddp_cedar.sh --tcp_port 19582 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p3
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_esf_perc_0p3 scripts/submit_ddp_cedar.sh --tcp_port 19583 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_perc_0p3
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_esf_perc_0p05 scripts/submit_ddp_cedar.sh --tcp_port 19584 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_perc_0p05
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_esf_perc_0p1 scripts/submit_ddp_cedar.sh --tcp_port 19585 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_perc_0p1
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_esf_perc_0p4 scripts/submit_ddp_cedar.sh --tcp_port 19586 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_perc_0p4
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_esf_weight scripts/submit_ddp_cedar.sh --tcp_port 19587 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_weight
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_iou_perc_0p05 scripts/submit_ddp_cedar.sh --tcp_port 19588 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p05
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_iou_perc_0p1 scripts/submit_ddp_cedar.sh --tcp_port 19589 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p1
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_iou_perc_0p2 scripts/submit_ddp_cedar.sh --tcp_port 19590 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p2
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_iou_perc_0p4 scripts/submit_ddp_cedar.sh --tcp_port 19591 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p4
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_iou_perc_0p5 scripts/submit_ddp_cedar.sh --tcp_port 19592 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p5
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_iou_weight scripts/submit_ddp_cedar.sh --tcp_port 19593 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_weight
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_iou_perc_0p3_iou_wt scripts/submit_ddp_cedar.sh --tcp_port 19594 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p3_iou_weight
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_perc_0p3_esf_wt scripts/submit_ddp_cedar.sh --tcp_port 19595 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_perc_0p3_esf_weight
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_iou_thresh_0p6 scripts/submit_ddp_cedar.sh --tcp_port 19596 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_thresh_0p6_lower_bs_epochs_data
sbatch --time=1:30:00 --array=1-1%1 --job-name=fine1lr_ptrcnn_esf_thresh_0p2 scripts/submit_ddp_cedar.sh --tcp_port 19597 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_thresh_0p2

sbatch --time=1:30:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_ptrcnn_iou_thresh_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19451 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_thresh_0p3
sbatch --time=1:30:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_ptrcnn_iou_thresh_0p4 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19452 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_thresh_0p4
sbatch --time=1:30:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_ptrcnn_iou_thresh_0p5 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19453 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_thresh_0p5
sbatch --time=1:30:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_ptrcnn_iou_thresh_0p7 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19454 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_iou_thresh_0p7
sbatch --time=1:30:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_ptrcnn_esf_thresh_0p1 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19455 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_thresh_0p1
sbatch --time=1:30:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_ptrcnn_esf_thresh_0p3 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19456 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_thresh_0p3
sbatch --time=1:30:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_ptrcnn_esf_thresh_0p4 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19457 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_thresh_0p4
sbatch --time=1:30:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_ptrcnn_esf_perc_0p2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19458 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_perc_0p2
sbatch --time=1:30:00 --nodes=1 --ntasks=1 --array=1-1%1 --job-name=fine1lr_ptrcnn_esf_perc_0p5 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19459 --downstream --cfg_file configs/waymo_fine1lr_pointrcnn.yaml --pretrained_ckpt checkpoint-ep49.pth.tar --model_name pointrcnn_pretrain_backbone_esf_perc_0p5


##################### Final ###############

#narval
sbatch --time=5:00:00 --nodes=1 --ntasks=1 --array=1-30%1 --job-name=ptrcnn_iou_perc_0p3_w10 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19325 --cfg_file configs/waymo_pointrcnn_iou_perc_0p3_waymo10.yaml
sbatch --time=5:00:00 --nodes=1 --ntasks=1 --array=1-30%1 --job-name=ptrcnn_segcontrast_w10 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19326 --cfg_file configs/waymo_pointrcnn_segcontrast_waymo10.yaml

#cedar
# Pointrcnn pretrain stage1
sbatch --time=5:00:00 --nodes=2 --ntasks=2 --array=1-10%1 --job-name=ptrcnn_iou_perc_0p3_w10 scripts/submit_ddp_cedar.sh --tcp_port 19325 --cfg_file configs/waymo_pointrcnn_iou_perc_0p3_waymo10.yaml
sbatch --time=5:00:00 --nodes=2 --ntasks=2 --array=1-10%1 --job-name=ptrcnn_segcontrast_w10 scripts/submit_ddp_cedar.sh --tcp_port 19326 --cfg_file configs/waymo_pointrcnn_segcontrast_waymo10.yaml

# # Pointrcnn pretrain stage2
#adjust batchsize to fit in cedar
# sbatch --time=1:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=ptrcnn_iou_perc_0p3_w10_stage2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19325 --cfg_file configs/waymo_pointrcnn_iou_perc_0p3_waymo10_stage2.yaml
# sbatch --time=1:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=ptrcnn_segcontrast_w10_stage2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19326 --cfg_file configs/waymo_pointrcnn_segcontrast_waymo10_stage2.yaml

# # Pointrcnn linear probe stage1
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=lpseg_ptrcnn_iou_perc_0p3_w10 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19335 --downstream --cfg_file configs/waymo_lpseg_pointrcnn.yaml --linear_probe_last_n_ckpts 10 --model_name pointrcnn_pretrain_iou_perc_0p3_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=lpseg_ptrcnn_segcontrast_w10 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19336 --downstream --cfg_file configs/waymo_lpseg_pointrcnn.yaml --linear_probe_last_n_ckpts 10 --model_name pointrcnn_pretrain_segcontrast_waymo10

# # Pointrcnn linear probe stage2
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=lpseg_ptrcnn_iou_perc_0p3_w10_stage2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19345 --downstream --cfg_file configs/waymo_lpseg_pointrcnn.yaml --linear_probe_last_n_ckpts 10 --model_name pointrcnn_pretrain_iou_perc_0p3_waymo10_stage2
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=lpseg_ptrcnn_segcontrast_w10_stage2 scripts/submit_ddp_compute_canada_waymo_multinode.sh --tcp_port 19346 --downstream --cfg_file configs/waymo_lpseg_pointrcnn.yaml --linear_probe_last_n_ckpts 10 --model_name pointrcnn_pretrain_segcontrast_waymo10_stage2

#minkunet pretrain
sbatch --time=5:00:00 --nodes=2 --ntasks=2 --array=1-10%1 --job-name=mink_segcontrast_w10 scripts/submit_ddp_cedar.sh --tcp_port 19631 --cfg_file configs/waymo_minkunet_segcontrast_waymo10.yaml
sbatch --time=5:00:00 --nodes=2 --ntasks=2 --array=1-10%1 --job-name=mink_iou_perc_0p3_w10 scripts/submit_ddp_cedar.sh --tcp_port 19621 --cfg_file configs/waymo_minkunet_iou_perc_0p3_waymo10.yaml

# #minkunet linear probe
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=lpseg_mink_segcontrast_w10 scripts/submit_ddp_cedar.sh --tcp_port 19631 --downstream --cfg_file configs/waymo_lpseg_minkunet.yaml --linear_probe_last_n_ckpts 10 --model_name minkunet_pretrain_segcontrast_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=lpseg_mink_iou_perc_0p3_w10 scripts/submit_ddp_cedar.sh --tcp_port 19621 --downstream --cfg_file configs/waymo_lpseg_minkunet.yaml --linear_probe_last_n_ckpts 10 --model_name minkunet_pretrain_iou_perc_0p3_waymo10

# #minkunet finetune one lr
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine1lr_e15_mink_segcontrast_w10 scripts/submit_ddp_cedar.sh --tcp_port 19641 --downstream --cfg_file configs/waymo_fine1lr_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --model_name minkunet_pretrain_segcontrast_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine1lr_e15_mink_iou_perc_0p3_w10 scripts/submit_ddp_cedar.sh --tcp_port 19651 --downstream --cfg_file configs/waymo_fine1lr_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --model_name minkunet_pretrain_iou_perc_0p3_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine1lr_e30_mink_segcontrast_w10 scripts/submit_ddp_cedar.sh --tcp_port 19641 --downstream --cfg_file configs/waymo_fine1lr_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 30 --model_name minkunet_pretrain_segcontrast_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine1lr_e30_mink_iou_perc_0p3_w10 scripts/submit_ddp_cedar.sh --tcp_port 19651 --downstream --cfg_file configs/waymo_fine1lr_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 30 --model_name minkunet_pretrain_iou_perc_0p3_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine1lr_e60_mink_segcontrast_w10 scripts/submit_ddp_cedar.sh --tcp_port 19641 --downstream --cfg_file configs/waymo_fine1lr_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 60 --model_name minkunet_pretrain_segcontrast_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine1lr_e60_mink_iou_perc_0p3_w10 scripts/submit_ddp_cedar.sh --tcp_port 19651 --downstream --cfg_file configs/waymo_fine1lr_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 60 --model_name minkunet_pretrain_iou_perc_0p3_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine1lr_e100_mink_segcontrast_w10 scripts/submit_ddp_cedar.sh --tcp_port 19641 --downstream --cfg_file configs/waymo_fine1lr_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 100 --model_name minkunet_pretrain_segcontrast_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine1lr_e100_mink_iou_perc_0p3_w10 scripts/submit_ddp_cedar.sh --tcp_port 19651 --downstream --cfg_file configs/waymo_fine1lr_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 100 --model_name minkunet_pretrain_iou_perc_0p3_waymo10

# #minkunet finetune two lrs
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine2lrs_e15_mink_segcontrast_w10 scripts/submit_ddp_cedar.sh --tcp_port 19661 --downstream --cfg_file configs/waymo_fine2lrs_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --model_name minkunet_pretrain_segcontrast_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine2lrs_e15_mink_iou_perc_0p3_w10 scripts/submit_ddp_cedar.sh --tcp_port 19671 --downstream --cfg_file configs/waymo_fine2lrs_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --model_name minkunet_pretrain_iou_perc_0p3_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine2lrs_e30_mink_segcontrast_w10 scripts/submit_ddp_cedar.sh --tcp_port 19661 --downstream --cfg_file configs/waymo_fine2lrs_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 30 --model_name minkunet_pretrain_segcontrast_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine2lrs_e30_mink_iou_perc_0p3_w10 scripts/submit_ddp_cedar.sh --tcp_port 19671 --downstream --cfg_file configs/waymo_fine2lrs_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 30 --model_name minkunet_pretrain_iou_perc_0p3_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine2lrs_e60_mink_segcontrast_w10 scripts/submit_ddp_cedar.sh --tcp_port 19661 --downstream --cfg_file configs/waymo_fine2lrs_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 60 --model_name minkunet_pretrain_segcontrast_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine2lrs_e60_mink_iou_perc_0p3_w10 scripts/submit_ddp_cedar.sh --tcp_port 19671 --downstream --cfg_file configs/waymo_fine2lrs_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 60 --model_name minkunet_pretrain_iou_perc_0p3_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine2lrs_e100_mink_segcontrast_w10 scripts/submit_ddp_cedar.sh --tcp_port 19661 --downstream --cfg_file configs/waymo_fine2lrs_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 100 --model_name minkunet_pretrain_segcontrast_waymo10
# sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-5%1 --job-name=fine2lrs_e100_mink_iou_perc_0p3_w10 scripts/submit_ddp_cedar.sh --tcp_port 19671 --downstream --cfg_file configs/waymo_fine2lrs_minkunet.yaml --pretrained_ckpt checkpoint-ep99.pth.tar --epochs 100 --model_name minkunet_pretrain_iou_perc_0p3_waymo10

# minkunet scratch
sbatch --time=5:00:00 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=scratch_mink_e15 scripts/submit_ddp_cedar.sh --tcp_port 19941 --downstream --cfg_file configs/waymo_scratch_minkunet.yaml --pretrained_ckpt checkpoint-ep0.pth.tar
sbatch --time=2:00:00 --dependency=afterok:21730724 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=scratch_mink_e30 scripts/submit_ddp_cedar.sh --tcp_port 19941 --downstream --cfg_file configs/waymo_scratch_minkunet.yaml --pretrained_ckpt checkpoint-ep0.pth.tar --epochs 30
sbatch --time=4:00:00 --dependency=afterok:21742792 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-1%1 --job-name=scratch_mink_e60 scripts/submit_ddp_cedar.sh --tcp_port 19941 --downstream --cfg_file configs/waymo_scratch_minkunet.yaml --pretrained_ckpt checkpoint-ep0.pth.tar --epochs 60
sbatch --time=6:00:00 --dependency=afterok:21742802 --account=def-swasland-ab --gres=gpu:v100l:4 --mem=180G --nodes=1 --ntasks=1 --array=1-2%1 --job-name=scratch_mink_e100 scripts/submit_ddp_cedar.sh --tcp_port 19941 --downstream --cfg_file configs/waymo_scratch_minkunet.yaml --pretrained_ckpt checkpoint-ep0.pth.tar --epochs 100


sbatch --time=1:30:00 --array=1-1%1 --job-name=scratch_ptrcnn_e15 scripts/submit_ddp_cedar.sh --tcp_port 19941 --downstream --cfg_file configs/waymo_scratch_pointrcnn.yaml --pretrained_ckpt checkpoint-ep0.pth.tar --downstream_model_dir scratch_epochs15