# python -m torch.distributed.launch --nproc_per_node=1 tools/main_dist.py --launcher pytorch --multiprocessing-distributed --cfg configs/waymo_pointrcnn_pseudo8_test.yaml
# python tools/main_dist.py --cfg configs/waymo_pointrcnn_pseudo8_test.yaml
wb_extra_tags: ['minkunet', 'waymo', 'pretrain_segmentation']
resume: true
num_workers: 4 # should be same as (16 --cpus-per-task i.e. per node)/(4 gpus per node)

log2tb: false
log2wb: true

test_freq: 1 #save chkp after every <freq> epochs, resume will load the last saved chkp
print_freq: 1 #print progress after processing every <freq> iters or batches
ckpt_save_interval: 1 #save only models to finetune for object detection
save_ckpt_after_epochs: 0

WANDB:
  ENABLED: True 
  PROJECT: SSL3dObject
  ENTITY: trailab
  SUMMARY_HIGHEST_METRIC: None
  dir: '/DepthContrast/output'

dataset:
  DATASET_NAMES: [WaymoDataset]
  PROCESSED_DATA_TAG: 'waymo_processed_data_v_1_2_0' #single return, but waymo_short has second return as well
  DATA_SPLIT: {'train': train}
  DATA_PATH: 'data/waymo'
  FRAME_SAMPLING_INTERVAL: {'train': 20} # 1/3rd of waymo pick every 10th frame to pretrain on so 10% waymo, if it is 2 then it is (1/2)=50% waymo
  BATCHSIZE_PER_REPLICA: 8 #Change to 14, if input moco feats is false, use 8
  POINT_CLOUD_RANGE:  [-75.2, -75.2, -2, 75.2, 75.2, 4]
  CLASS_NAMES: ['Object']

  POINT_TRANSFORMS: # comment all except ToTensorLidar for linear probe
    - NAME: random_world_flip
      ALONG_AXIS_LIST: ['x', 'y']
    - NAME: random_world_rotation
      WORLD_ROT_ANGLE: [-0.78539816, 0.78539816] #-45deg, + 45deg
    - NAME: random_world_scaling
      WORLD_SCALE_RANGE: [0.95, 1.05]
    - NAME: random_local_translation
      LOCAL_TRANSLATION_RANGE: [-0.3, 0.3]
      ALONG_AXIS_LIST: ['x', 'y']
    - NAME: random_local_rotation
      LOCAL_ROT_ANGLE: [-0.78539816, 0.78539816]
    - NAME: random_local_scaling
      LOCAL_SCALE_RANGE: [0.95, 1.05]
    - NAME: random_drop_n_cuboids

  SAMPLE_NUM_POINTS: 20000
  INPUT: sparse_tensor
  RESOLUTION: 0.05
  # EXTRACT_SHAPE_DESCRIPTORS: esf

  COLLATE_FUNCTION: "sparse_moco_collator"
  DROP_LAST: True

optimizer:
  name: "sgd"
  weight_decay: 0.0001
  momentum: 0.9
  nesterov: True
  num_epochs: 50
  lr:
    name: "cosine"
    base_lr: 0.12 #0.1 for linear_probe #0.12

model:
  model_dir: "checkpoints/minkunet"
  name: "minkunet_pretrain_iou_knn_0p01_filter_waymo5_t0p04" 

  MODEL_BASE:
    NAME: Segmentor

    BACKBONE_3D:
      NAME: MinkUNet

    PRETEXT_HEAD: 
      NAME: ProjectionSparseVoxHead
      cluster: True
      use_mlp: True
      mlp_dim: [96, 128, 128]


NCE_LOSS:
  LOSS_WEIGHT: 1.0
  TEMPERATURE: 0.04
  NUM_NEGATIVES: 65536
  EMBEDDING_DIM: 128
  IOU_QUANTILE_THRESHOLD: 0.01 #% of 65536 i.e. 6.55 neg samples removed

  