# python -m torch.distributed.launch --nproc_per_node=1 tools/main_dist.py --launcher pytorch --multiprocessing-distributed --cfg configs/waymo.yaml
# python tools/main_dist.py --cfg configs/waymo.yaml
wb_extra_tags: ['centerpoint', 'waymo', 'pretrain_object_detection']
resume: true
num_workers: 4 # should be same as  (16 --cpus-per-task i.e. per node)/(4 gpus per node)

log2tb: false
log2wb: true

test_freq: 1 #save chkp after every <freq> epochs, resume will load the last saved chkp
print_freq: 1 #print progress after processing every <freq> iters or batches
ckpt_save_interval: 1 #save only models to finetune for object detection
save_ckpt_after_epochs: 0

WANDB:
  ENABLED: True 
  PROJECT: SSL3dObject
  ENTITY: trailab
  SUMMARY_HIGHEST_METRIC: None
  dir: '/DepthContrast/output'

dataset:
  DATASET_NAMES: [WaymoDataset]
  PROCESSED_DATA_TAG: 'waymo_processed_data_v_1_2_0' #'waymo_processed_data_v_1_2_0' #single return, but waymo_short has second return as well
  DATA_SPLIT: {'train': train}
  DATA_PATH: 'data/waymo'
  FRAME_SAMPLING_INTERVAL: {'train': 20} #1/4th of waymo
  BATCHSIZE_PER_REPLICA: 8 #Change to 14, if input moco feats is false, use 8
  POINT_CLOUD_RANGE:  [-75.2, -75.2, -2, 75.2, 75.2, 4] #[  0. , -75. ,  -3. ,  75. ,  75. ,   3. ] 
  CLASS_NAMES: ['Vehicle', 'Pedestrian', 'Cyclist', 'OtherSmall', 'OtherMedium', 'OtherLong', 'OtherLonger', 'OtherBig'] #['Vehicle', 'Pedestrian', 'Cyclist']
  MEAN_SIZES: [[4.7, 2.1, 1.7],
                [0.91, 0.86, 1.73],
                [1.78, 0.84, 1.78],
                [0.5, 0.5, 1.0],
                [3, 2, 1.5],
                [10, 2.5, 1.7],
                [20, 2.5, 1.7],
                [20, 20, 1.7]]
  

  POINT_TRANSFORMS: # comment all except ToTensorLidar for linear probe
    - NAME: random_world_flip
      ALONG_AXIS_LIST: ['x', 'y']
    - NAME: random_world_rotation
      WORLD_ROT_ANGLE: [-0.78539816, 0.78539816] #-45deg, + 45deg
    - NAME: random_world_scaling
      WORLD_SCALE_RANGE: [0.95, 1.05]
    - NAME: random_local_translation
      LOCAL_TRANSLATION_RANGE: [-0.3, 0.3]
      ALONG_AXIS_LIST: ['x', 'y']
    - NAME: random_local_rotation
      LOCAL_ROT_ANGLE: [-0.78539816, 0.78539816]
    - NAME: random_local_scaling
      LOCAL_SCALE_RANGE: [0.95, 1.05]

    # - NAME: random_cuboid_lidar
    #   npoints: 10000
    # - NAME: random_drop

  SAMPLE_NUM_POINTS: 20000
  
  VOX: True

  COLLATE_FUNCTION: "moco_collator"
  DROP_LAST: True

optimizer:
  name: "sgd"
  weight_decay: 0.0001
  momentum: 0.9
  nesterov: True
  num_epochs: 10
  lr:
    name: "cosine"
    base_lr: 0.012 #0.1 for linear_probe #0.12

model:
  model_dir: "checkpoints/centerpoint"
  name: "centerpoint_pretrain_pseudo_8_lr0p012_1node" 
  VOX: True

  MODEL_BASE:
    NAME: CenterPoint

    VFE:
      NAME: MeanVFE

    BACKBONE_3D:
      NAME: VoxelResBackBone8x

    MAP_TO_BEV:
      NAME: HeightCompression
      NUM_BEV_FEATURES: 256

    BACKBONE_2D:
      NAME: BaseBEVBackbone

      LAYER_NUMS: [5, 5]
      LAYER_STRIDES: [1, 2]
      NUM_FILTERS: [128, 256]
      UPSAMPLE_STRIDES: [1, 2]
      NUM_UPSAMPLE_FILTERS: [256, 256]


    PRETEXT_HEAD: 
      NAME: SegVoxHead
      num_keypts: 20000 # num keypts to sample from fg pts in a pc
      use_mlp: True
      mlp_dim: [768, 128, 128]

  MODEL_DET_HEAD:
    NAME: CenterPoint

    INPUT_MOCO_FEATS: False

    DENSE_HEAD:
      NAME: CenterHead
      CLASS_AGNOSTIC: False # does not work
      INPUT_FEATURES: 512

      CLASS_NAMES_EACH_HEAD: [
          ['Vehicle', 'Pedestrian', 'Cyclist', 'OtherSmall', 'OtherMedium', 'OtherLong', 'OtherLonger', 'OtherBig']
      ]

      SHARED_CONV_CHANNEL: 64
      USE_BIAS_BEFORE_NORM: True
      NUM_HM_CONV: 2
      SEPARATE_HEAD_CFG:
          HEAD_ORDER: ['center', 'center_z', 'dim', 'rot']
          HEAD_DICT: {
              'center': {'out_channels': 2, 'num_conv': 2},
              'center_z': {'out_channels': 1, 'num_conv': 2},
              'dim': {'out_channels': 3, 'num_conv': 2},
              'rot': {'out_channels': 2, 'num_conv': 2},
          }

      TARGET_ASSIGNER_CONFIG:
          FEATURE_MAP_STRIDE: 8
          NUM_MAX_OBJS: 500
          GAUSSIAN_OVERLAP: 0.1
          MIN_RADIUS: 2

      LOSS_CONFIG:
          LOSS_WEIGHTS: {
              'cls_weight': 1.0,
              'loc_weight': 2.0,
              'code_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
              'class_wise_cls_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.5, 0.5],
              'class_wise_reg_weights': [1.0, 1.0, 1.0, 1.0, 1.0, 0.5, 0.0, 0.0]
          }
    
  # MODEL_AUX_HEAD:
  #   NAME: CenterPoint
    
  #   PRETEXT_HEAD: 
  #     NAME: RegHead
  #     REG_FC: [256, 256]
  #     # - NAME: ScaleRegHead
  #     #   REG_FC: [256, 256]
  #     LOSS_CONFIG:
  #       LOSS_REG: WeightedSmoothL1Loss
  #       LOSS_WEIGHTS: {
  #           'seg_reg_weight': 1.0,
  #           'code_weights': [1.0, 1.0]
  #       }

NCE_LOSS:
  LOSS_WEIGHT: 1.0
  TEMPERATURE: 0.1
  NUM_NEGATIVES: 65536
  EMBEDDING_DIM: 128
  IOU_FILTER: True