wb_extra_tags: ['pointnet', 'dense_kitti', 'depth_contrast', 'weather_aug']
resume: true
linear_probe: false # True for linear probe
cluster: False
num_workers: 8

log2tb: true
log2wb: true

test_freq: 1 # save chkp after every <freq> epochs, resume will load the last saved chkp
print_freq: 100 # print progress after processing every <freq> iters or batches
ckpt_save_interval: 20
save_ckpt_after_epochs: 100

WANDB:
  ENABLED: True
  PROJECT: DepthContrast_dense
  ENTITY: trailab
  SUMMARY_HIGHEST_METRIC: None
  dir: '/DepthContrast/output'

dataset:
  BATCHSIZE_PER_REPLICA: 14
  APPLY_WEATHER_AUG: True # False for linear probe
  DATASET_NAMES: [DenseKittiDataset]
  # SEMANTIC_KITTI:
  #   train: [ '00', '01', '02', '03', '04', '05', '06', '07', '09', '10' ]
  #   val: ['08']
  INFO_PATHS: 
    train: ['kitti_infos_all.pkl', 'dense_infos_train_all_FOV3000_60.pkl'] 
    val: ['dense_infos_val_all_FOV3000_15.pkl']
  LABEL_TYPE: objects #sample_index, objects, class_names
  DATA_TYPE: points
  SENSOR_TYPE: 'hdl64'
  SIGNAL_TYPE: 'strongest'
  Lidar: True
  VOX: False
  DROR: 0.45
  UPSAMPLE: '1in1'
  COUPLED: True
  WET_SURFACE: '1in10' #'1in10'
  SNOW: 'uniform_gunn_1in2' #'1in10'
  FOG_AUGMENTATION: 'CVL_1in2'
  FOG_NOISE_VARIANT: 'v2'
  FOG_GAIN: True
  FOV_POINTS_ONLY: True
  POINT_TRANSFORMS: # comment all except ToTensorLidar for linear probe
    - name: randomcuboidLidar
      crop: 0.5
      npoints: 10000
      randcrop: 1.0
      aspect: 0.75
    - name: randomdrop
      crop: 0.2
    - name: RandomFlipLidar
    - name: RandomRotateLidar
    - name: RandomScaleLidar
    - name: ToTensorLidar
  COLLATE_FUNCTION: "point_moco_collator"
  DROP_LAST: True

optimizer:
  name: "sgd"
  weight_decay: 0.0001
  momentum: 0.9
  nesterov: True
  num_epochs: 401
  lr:
    name: "cosine"
    base_lr: 0.12 #0.1 for linear_probe

model:
  name: "dc_1in2_cube_up_dense_kitti"
  model_dir: "checkpoints/pointnetMSG_train_all_FOV3000_60/dc"
  model_input: ["points", "points_moco"]
  Lidar: True
  VOX: False
  arch_point: "pointnet_msg"
  linear_probe_dim: [128, 2]
  args_point:
    use_mlp: True
    mlp_dim: [128, 128, 128]

loss:
  args:
    TEMPERATURE: 0.1
    NUM_NEGATIVES: 21995 #Waymo:65536, SemKitti=19130,  Dense: 6996, Kitti: 14999, Dense+kitti+SemKitti= 41125, Dense+Semkitti=26126, Dense+Kitti: 21995, Dense_train_all_60: 6996
    EMBEDDING_DIM: 128
