wb_extra_tags: ['pointnet', 'train_all_FOV3000_60', 'dc_vdc']
resume: true
linear_probe: false # True for linear probe
num_workers: 8

log2tb: true
log2wb: true

test_freq: 1 # save chkp after every <freq> epochs, resume will load the last saved chkp
print_freq: 100 # print progress after processing every <freq> iters or batches
ckpt_save_interval: 20
save_ckpt_after_epochs: 300

WANDB:
  ENABLED: True
  PROJECT: DepthContrast_dense
  ENTITY: trailab
  SUMMARY_HIGHEST_METRIC: None
  dir: '/DepthContrast/output'

dataset:
  DATASET_NAMES: [DenseDataset]
  INFO_PATHS: 
    train: ['dense_infos_train_all_FOV3000_60.pkl']
    val: ['dense_infos_val_all_FOV3000_15.pkl']
  BATCHSIZE_PER_REPLICA: 16
  LABEL_TYPE: objects #sample_index, objects, class_names
  DATA_TYPE: points
  SENSOR_TYPE: 'hdl64'
  SIGNAL_TYPE: 'strongest'
  Lidar: True
  VOX: False
  APPLY_WEATHER_AUG: True # False for linear probe
  DROR: 0.45
  UPSAMPLE: '1in1'
  COUPLED: False
  WET_SURFACE: '1in10' #'1in10'
  SNOW: 'uniform_gunn_1in10' #'1in10'
  FOG_AUGMENTATION: 'CVL_1in10'
  FOG_NOISE_VARIANT: 'v2'
  FOG_GAIN: True
  FOV_POINTS_ONLY: True
  POINT_TRANSFORMS: # comment all except ToTensorLidar for linear probe
    - name: RandomFlipLidar
    - name: RandomRotateLidar
    - name: RandomScaleLidar
    - name: ToTensorLidar
  COLLATE_FUNCTION: "point_moco_collator"
  INPUT_KEY_NAMES: ["points", "points_moco"]
  DROP_LAST: True

optimizer:
  name: "sgd"
  weight_decay: 0.0001
  momentum: 0.9
  nesterov: False
  num_epochs: 401
  lr:
    name: "cosine"
    base_lr: 0.15 #0.1 for linear_probe
    final_lr: 0.0001 #0 for linear_probe

model:
  name: "dc_vdc_snow1in10_wet_fog1in10_cubeF_upsample_FOV3000_lr0p15"
  model_dir: "checkpoints/pointnetMSG_train_all_FOV3000_60/dc_vdc"
  model_input: ["points", "points_moco"]
  model_feature: [["dc_feats", "vdc_feats"], ["dc_feats", "vdc_feats"]]
  Lidar: True
  VOX: False
  arch_point: "pointnet_msg"
  linear_probe_dim: [128, 2]
  args_point:
    use_mlp: True
    mlp_dim: [128, 128, 128]

loss:
  name: "NCELossMoco"
  args:
    model_type: DC_VDC #DC, VDC
    LOSS_TYPE: NPID
    within_format_weight0: 1.0
    within_format_weight1: 0.5
    NCE_LOSS:
      NORM_EMBEDDING: True
      TEMPERATURE: 0.1
      LOSS_TYPE: cross_entropy
      NUM_NEGATIVES: 65536 # has to be divisble by batch size or num voxels in each point cloud
      EMBEDDING_DIM: 128

# Linear Probe
# loss:
#   name: "FocalLoss"
#   args:
#     num_classes: 1 #4 #1 #num_classes does not include background class i.e. [car, pedestrian]
#     alpha: None #[0.6, 0.1, 0.1, 0.1, 0.1] if None, then class weights are calc as 1/class_freq
#     gamma: 0
#     reduction: 'mean'
#     ignore_index: -100 # don't ignore any class if objects
